### PR TITLE
Portuguese dictionary and python script

### PR DESCRIPTION
**Pull request by enriquefynn**
The Portuguese is generated by the python script find_words.py, I don't know if the scope of the project is to have this kind of scripts in it, but I think it will help people make their own native language bip39 wordlist

### CODE REVIEW

**Comment by jprichardson** [comment]
This will bloat the package. I'm against this. However, I'm in favor of creating `bip39-portuguese` or `bip39-lang-pt` (named whatever) that exports the wordlist and `bip39` could use the list.

It's ultimately up to @weilu and @dcousens.

**Comment by enriquefynn** [comment]
Now that I'm thinking, this is not good at all, it mixes things that should do different stuff, I'm closing the pull request and doing one only with the portuguese list, thanks.

**Comment by dcousens** [comment]
Thanks @enriquefynn,  that'd be great.

**Comment by dcousens** [comment]
@jprichardson I'm thinking as long as the word lists aren't in the main export, it shouldn't affect those who will be size concious.

**Comment by dcousens** [comment]
I intend to do that export style for the next release,  unless we think of something else.

**Pull request closed without merging**
