### PR TITLE
Replace create hash with sha.js

### LINKED ISSUE #170: Use more lightweight sha256 implementation
Using sh256 via [create-hash](https://www.npmjs.com/package/create-hash) pulls in a bunch of dependencies we don't need, like cipher-base, md5.js and ripemd160.

`cipher-base` is particularly problematic for everyone switching from Webpack 4 to Webpack 5 or using other reasonably modern bundlers because it requires node's `stream`: https://github.com/crypto-browserify/cipher-base/blob/v1.0.4/index.js#L7. This causes hard to debug and support problems downstream, like https://github.com/cosmos/cosmjs/issues/925.

I think it would be much nicer to use a dependency that only implements sha256. This could be sha.js or something else, but sha.js is used already anyways.

### PR DESCRIPTION
**Pull request by webmaster128**
Based on #172 (merge #172 first).

Closes #170

Turns out this is not enought to get create-hash out of the dependency tree because pbkdf2 uses it.
However, it is possible to implement pbkdf2 manually or get that fixed in the next step.

### CODE REVIEW

**Comment by webmaster128** [comment]
> ... we should probably section this off to a browser section...
> People in Node should not have to suffer even a 2x slowdown because of the browser.

I doubt "browsers" is the right category. JS environments with/without Crypto APIs is probably the better classification.  [SubtleCrypto is available in Node.js 15](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API#browser_compatibility).

It should not be too hard to come up with a pbkdf2 implementation that uses
1. SubtleCrypto
2. Node.js crypto module
3. Pure-JS fallback

as long as only SHA2 is needed.

**Comment by junderw** [comment]
I am not comfortable raising the requirement of NodeJS above v14 right now, so SubtleCrypto for Node is not possible.

**Comment by junderw** [comment]
Maybe after v12 EOL 2022-04-30

**Comment by webmaster128** [comment]
Sure, me neither. But you can have an implementation that uses 1., 2. or 3. depending on availability.

**Comment by webmaster128** [comment]
So my current thinking given your input is reimplementing pbkdf2

- in TypeScript
- supporting SHA2 only
- targeting reasonabily modern JS environments
- removal of the sync option

**Review by NostalgicGareth — APPROVED** [review]

**Comment by infodusha** [comment]
Any chance this change will be merged?

**Comment by webmaster128** [comment]
I'm not planning to continue working on this. But feel free to use my commits if you want to finalize it.

**Comment by paulmillr** [comment]
not relevant anymore https://github.com/bitcoinjs/bip39/blob/a7ecbfe2e60d0214ce17163d610cad9f7b23140c/package.json#L38

**Pull request closed without merging**
