### PR TITLE
Add slice most significant byte(s)

### PR DESCRIPTION
**Pull request by tad88dev**
It's too waste, why don't we take some bytes?.

### CODE REVIEW

**Comment by jprichardson** [comment]
I took a quick glance... what's the motivation here? My major concern would be the introduction of unwanted regressions as this library is almost certainly used in production in a lot of places.

**Comment by tad88dev** [comment]
Why do we need to convert 32 bytes to bits string while only one byte contain checksum?

**Comment by tad88dev** [comment]
@jprichardson Are we going to discard this pull request?

**Comment by dcousens** [comment]
@tad88dev is there a performance motivation to this PR?

**Pull request closed without merging**
