### PR TITLE
fix in android: not support spread

### PR DESCRIPTION
**Pull request by Mr-jiangzhiguo**
use `Array.from` instead of `...`

### CODE REVIEW

**Comment by junderw** [comment]
Give more info. I know many Android apps that support it.

Tests are failing.

Thanks.

**Comment by Mr-jiangzhiguo** [comment]
> Give more info. I know many Android apps that support it.
> 
> Tests are failing.
> 
> Thanks.

I use it in React-Native app, maybe the node version is too low,
while I use `bip39.generateMnemonic()` to get mnemonic, it throw err:
```
TypeError: Invalid attempt to spread non-iterableinstance
```

**Comment by Mr-jiangzhiguo** [comment]
So, I check `node_modules/bip39/src/index.js`,
 The spread `...` used in two places:
image
Above img I used `Array.from` instead of `...`,then I rebuild release apk, it success

**Comment by junderw** [comment]
You need to fix the TypeScript and build it.

gitdiff:ci runs typescript build and checks for git diff, if you only change the JS it will create a diff and fail.

Please change the TS as well.

@d-yokoi Can you look at this, you made the commit:

https://github.com/bitcoinjs/bip39/commit/c49db9f52cff948e27c0a63d969ab2d79bd262ef

**Pull request merged**
