### PR TITLE
add alternative to #17

### PR DESCRIPTION
**Pull request by dcousens**
Exposes word lists,  such that if more are added,  they can easily be merged.

### CODE REVIEW

**Comment by dcousens** [comment]
Thoughts @peter-conalgo / @grabus ?

**Comment by peter-conalgo** [comment]
Personal preference, but I'd rather the key was "EN" instead of "english".

**Comment by jprichardson** [comment]
> Personal preference, but I'd rather the key was "EN" instead of "english".

`EN` or `en` would be my preference, probably `en`.

**Comment by weilu** [comment]
I'm all for standards: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

**Comment by dcousens** [comment]
@weilu, so `EN`?

**Comment by weilu** [comment]
@dcousens I'm down with that.

**Comment by dcousens** [comment]
@jprichardson I went with `EN`,  as its more indicative of a constant IMHO.

**Comment by dcousens** [comment]
@weilu added a test in https://github.com/bitcoinjs/bip39/commit/f263412660b6f04f6eb7759e5c57f88dfbd69972

**Comment by weilu** [comment]
:+1:

**Pull request merged**
