### PR TITLE
Export the wordlist so it may be used by other code

### PR DESCRIPTION
**Pull request by peter-conalgo**
Nice code and I wanted to make use of the wordlist in my project, so I exported it.

Here is my pull request with this great innovation!

Thanks for the open-source code.. [Coinkite](https://coinkite.com)

### CODE REVIEW

**Comment by weilu** [comment]
@dcousens what would be the right way to export it?

**Comment by grabus** [comment]
It's really useful to have access to wordlist.
Are you going to merge it or it will be better to make own fork?

**Comment by dcousens** [comment]
@grabus the issue is,  what word list do you want?  In this case, we're only exporting the English word list...

**Comment by dcousens** [comment]
Opened https://github.com/weilu/bip39/pull/22 as an alternative which IMHO should be more future proof if we decide to add more word lists to this repository.

**Pull request closed without merging**
